services:
  bootstrap:
    image: alpine:latest
    container_name: bootstrap
    volumes:
      - ./mnt:/mnt
      - ./bootstrap.sh:/bootstrap.sh:ro
    command: ["/bin/sh", "/bootstrap.sh"]
    depends_on: []

  app:
    build: .
    container_name: app
    ports:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./mnt:/mnt
    environment:
      - HYPERVISOR=docker
    depends_on:
      bootstrap:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "25236:25236"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app


  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    env_file: .env
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_LOG_LEVEL: error
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "48123:8123"
      - "49440:9000"
    volumes:
      - ./mnt:/mnt
      - ./config.d:/etc/clickhouse-server/config.d:ro
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "-q", "localhost:8123"]
      interval: 5s
      timeout: 5s
      retries: 5

